/**
 * PR #142 review F-018 follow-up: the browser scrubSecrets agrees row-for-row
 * with contracts/scrub-secrets-vectors.json (expected values generated by the
 * desktop twin). The desktop test (desktop/src/__tests__/scrub-secrets-vectors.test.ts)
 * asserts the same file, so the two implementations cannot drift apart.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, test } from 'vitest';
import { scrubSecrets } from './provider-error';

interface Vec {
  name: string;
  key: string;
  input: string;
  expected: string;
}

const CONTRACTS = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..', 'contracts');
const cases = (JSON.parse(fs.readFileSync(path.join(CONTRACTS, 'scrub-secrets-vectors.json'), 'utf8')) as { cases: Vec[] }).cases;

describe('web scrubSecrets vs contracts/scrub-secrets-vectors.json', () => {
  test('vector file is non-trivial', () => {
    expect(cases.length).toBeGreaterThanOrEqual(12);
  });
  for (const c of cases) {
    test(c.name, () => {
      expect(scrubSecrets(c.input, c.key)).toBe(c.expected);
    });
  }
});
