#!/usr/bin/env python3
"""
Script to prepare files for Inno Setup installer creation.
This script prepares the necessary files and directories for bundling
the application with Python embeddable, wheels, models, and app source.
"""

import os
import shutil
import subprocess
from pathlib import Path

def create_directories():
    """Create the required directory structure for the installer."""
    dirs = [
        "build_installer/wheels",
        "build_installer/models",
        "build_installer/embeddings",
        "build_installer/app"
    ]
    
    for directory in dirs:
        os.makedirs(directory, exist_ok=True)
        print(f"Created directory: {directory}")

def download_wheels():
    """Download all required packages as wheels to build_installer/wheels/"""
    print("Downloading wheels...")
    
    # Ensure we're in the correct directory
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    
    try:
        # Run pip download to get all requirements as wheels
        subprocess.run([
            "pip", "download", 
            "--dest", "build_installer/wheels",
            "--no-deps",
            "-r", "requirements.txt"
        ], check=True)
        print("Successfully downloaded wheels to build_installer/wheels/")
    except subprocess.CalledProcessError as e:
        print(f"Error downloading wheels: {e}")
        raise

def copy_app_files():
    """Copy application source files to build_installer/app/"""
    print("Copying application files...")
    
    # Get list of all Python files in the root directory
    app_files = []
    for file in Path(".").rglob("*.py"):
        # Exclude build directories and cache files
        if not any(part in str(file) for part in ["build_installer", "__pycache__", ".git"]):
            app_files.append(file)
    
    # Add requirements.txt
    if Path("requirements.txt").exists():
        app_files.append(Path("requirements.txt"))
    
    # Copy files to build_installer/app/
    for file in app_files:
        destination = Path("build_installer/app") / file.name
        shutil.copy2(file, destination)
        print(f"Copied {file} to {destination}")

def prepare_embedding_model():
    """Instructions for preparing the sentence-transformers model"""
    print("Preparing embedding model...")
    
    # Create a README with instructions
    readme_content = """
# Embedding Model Preparation

The BAAI/bge-small-en-v1.5 model needs to be manually downloaded and placed in this directory.

Instructions:
1. Download the model from Hugging Face: https://huggingface.co/BAAI/bge-small-en-v1.5
2. Extract the model files and place them in this directory
3. The model files should include:
   - config.json
   - pytorch_model.bin (or model.safetensors)
   - tokenizer.json
   - tokenizer_config.json
   - vocab.txt
   - etc.

This model is used for embedding documents for semantic search.
"""
    
    with open("build_installer/embeddings/README.txt", "w") as f:
        f.write(readme_content)
    
    print("Created README.txt with instructions for embedding model")

def prepare_gguf_model():
    """Instructions for preparing the GGUF model"""
    print("Preparing GGUF model...")
    
    # Create a README with instructions
    readme_content = """
# GGUF Model Preparation

The Qwen3-1.7B GGUF model needs to be manually downloaded and placed in this directory.

Instructions:
1. Download the GGUF model file from a source (e.g., Hugging Face or ModelScope)
2. Place the .gguf file in this directory
3. The file should be named something like: qwen3-1.7b-q4_k_m.gguf

This model is used for LLM inference with llama-cpp-python.
"""
    
    with open("build_installer/models/README.txt", "w") as f:
        f.write(readme_content)
    
    print("Created README.txt with instructions for GGUF model")

def create_inno_setup_script():
    """Create Inno Setup script template"""
    print("Creating Inno Setup script...")
    
    inno_script = """
; Inno Setup script for Document QA App installer
; Generated by build_installer.py

[Setup]
AppName=Document QA Application
AppVersion=1.0.0
AppPublisher=Your Company Name
AppPublisherURL=https://yourcompany.com
AppSupportURL=https://yourcompany.com/support
AppUpdatesURL=https://yourcompany.com/updates
DefaultDirName={pf}\\DocumentQAApp
DisableDirPage=yes
DisableProgramGroupPage=yes
LicenseFile=LICENSE.txt
OutputDir=.
OutputBaseFilename=DocumentQAInstaller
Compression=lzma
SolidCompression=yes
PrivilegesRequired=lowest

[Files]
; Python embeddable distribution files
Source: "python_embeddable\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Wheels
Source: "build_installer\\wheels\\*"; DestDir: "{app}\\wheels"; Flags: ignoreversion recursesubdirs createallsubdirs

; App files
Source: "build_installer\\app\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Models
Source: "build_installer\\models\\*"; DestDir: "{app}\\models"; Flags: ignoreversion recursesubdirs createallsubdirs

; Embedding models
Source: "build_installer\\embeddings\\*"; DestDir: "{app}\\embeddings"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{commondesktop}\\Document QA App"; Filename: "{app}\\main.py"; WorkingDir: "{app}"

[Run]
Filename: "{app}\\main.py"; Description: "Launch Document QA App"; Flags: nowait postinstall skipifsilent

[Code]
; Add any custom code here if needed
"""
    
    with open("build_installer/setup.iss", "w") as f:
        f.write(inno_script)
    
    print("Created Inno Setup script: build_installer/setup.iss")

def main():
    """Main function that orchestrates the preparation steps."""
    print("Starting installer preparation...")
    
    # Create directories
    create_directories()
    
    # Download wheels
    download_wheels()
    
    # Copy application files
    copy_app_files()
    
    # Prepare models
    prepare_embedding_model()
    prepare_gguf_model()
    
    # Create Inno Setup script
    create_inno_setup_script()
    
    print("Installer preparation complete!")
    print("Next steps:")
    print("1. Manually place the GGUF model file in build_installer/models/")
    print("2. Manually download and place BAAI/bge-small-en-v1.5 model in build_installer/embeddings/")
    print("3. Download Python embeddable distribution and place in python_embeddable/ directory")
    print("4. Run Inno Setup with build_installer/setup.iss to create installer")

if __name__ == "__main__":
    main()