/**
 * Persistence guardrails for the desktop inference-mode seeding. Every
 * persisted mode boots into the desktop backend (B9). universal-provider-
 * settings-overhaul (AC8) reverses PR #138's "provider survives the re-seed":
 * external endpoints are generated by the backend now, so a legacy 'provider'
 * mode becomes 'api' too, keeps its providerConfig for the one-time desktop
 * migration, and is marked for it.
 */
import { describe, test, expect, beforeEach } from 'vitest';
import { seedInferenceModeForDesktop } from './desktop-seed';
import { LEGACY_PROVIDER_MARKER } from '../llm/external-migration';

const KEY = 'inference-mode';

describe('seedInferenceModeForDesktop', () => {
  beforeEach(() => {
    localStorage.clear();
  });

  test('a persisted legacy provider mode no longer displaces the backend (providerConfig kept for migration)', () => {
    localStorage.setItem(
      KEY,
      JSON.stringify({
        mode: 'provider',
        serverUrl: 'http://127.0.0.1:1',
        browserEngine: 'wllama',
        ragPreset: 'quality',
        providerConfig: { baseUrl: 'http://127.0.0.1:8080', model: 'local-model' },
      })
    );
    seedInferenceModeForDesktop('http://127.0.0.1:54321');
    const stored = JSON.parse(localStorage.getItem(KEY) ?? '{}') as Record<string, unknown>;
    expect(stored.mode).toBe('api');
    expect(stored.serverUrl).toBe('http://127.0.0.1:54321');
    expect(stored[LEGACY_PROVIDER_MARKER]).toBe(true);
    expect(stored.providerConfig).toEqual({
      baseUrl: 'http://127.0.0.1:8080',
      model: 'local-model',
    });
  });

  test('other persisted modes still boot into the desktop backend (B9 behavior)', () => {
    localStorage.setItem(
      KEY,
      JSON.stringify({ mode: 'browser-local', serverUrl: 'http://127.0.0.1:1' })
    );
    seedInferenceModeForDesktop('http://127.0.0.1:54321');
    const stored = JSON.parse(localStorage.getItem(KEY) ?? '{}') as Record<string, unknown>;
    expect(stored.mode).toBe('api');
    expect(stored.serverUrl).toBe('http://127.0.0.1:54321');
    expect(stored[LEGACY_PROVIDER_MARKER]).toBeUndefined();
  });

  test('an empty store boots into the desktop backend', () => {
    seedInferenceModeForDesktop('http://127.0.0.1:54321');
    const stored = JSON.parse(localStorage.getItem(KEY) ?? '{}') as Record<string, unknown>;
    expect(stored.mode).toBe('api');
  });

  test('provider mode with missing providerConfig also boots into the backend', () => {
    localStorage.setItem(KEY, JSON.stringify({ mode: 'provider' }));
    seedInferenceModeForDesktop('http://127.0.0.1:54321');
    const stored = JSON.parse(localStorage.getItem(KEY) ?? '{}') as Record<string, unknown>;
    expect(stored.mode).toBe('api');
  });
});
