/**
 * B9 (issue #67) desktop inference-mode seeding, extracted from App.tsx so the
 * persistence behavior is unit-testable without mounting the App import graph.
 *
 * Seeds the inference-mode store BEFORE InferenceModeProvider mounts so every
 * desktop launch boots in `api` mode pointed at the Electron backend. The
 * loopback port and launch token rotate on every app start, so this must run
 * with the FRESH session values each launch.
 *
 * universal-provider-settings-overhaul (AC8): PR #138's 'provider' mode is
 * retired — external endpoints are generated by the desktop backend itself —
 * so a persisted 'provider' mode no longer displaces the backend. It becomes
 * 'api' like every other stored mode, and the blob is marked so the one-time
 * migration (lib/llm/external-migration.ts) moves the legacy connection into
 * the backend's external.* settings once the desktop session exists.
 */

import { INFERENCE_MODE_KEY } from '../storage/persisted-keys';
import { LEGACY_PROVIDER_MARKER } from '../llm/external-migration';

export function seedInferenceModeForDesktop(baseUrl: string): void {
  let stored: Record<string, unknown> = {};
  try {
    // Harden the literal-'null'/'5'/garbage blob shapes (PR #138 review):
    // anything that is not a plain object reads as empty instead of throwing
    // during boot.
    const parsed: unknown = JSON.parse(localStorage.getItem(INFERENCE_MODE_KEY) ?? '{}');
    if (parsed !== null && typeof parsed === 'object' && !Array.isArray(parsed)) {
      stored = parsed as Record<string, unknown>;
    }
  } catch {
    stored = {};
  }
  if (stored.mode === 'provider') stored[LEGACY_PROVIDER_MARKER] = true;
  stored.mode = 'api';
  stored.serverUrl = baseUrl;
  localStorage.setItem(INFERENCE_MODE_KEY, JSON.stringify(stored));
}
